image: node:lts

pages:
  stage: deploy
  before_script:
  - npm install -g yarn
  - yarn install
  script:
  - yarn build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
